OVT_JobConfig {
 m_sTitle "#OVT-Job_AssassinateOfficer"
 m_sDescription "#OVT-Job_AssassinateOfficer_Description"
 m_bBaseOnly 1
 m_iReward 750
 m_iRewardXP 40
 m_aConditions {
  OVT_PlayerInRangeJobCondition "{6A7D9B2E00000061}" {
   m_iRange 2000
  }
  OVT_BaseIsOccupiedJobCondition "{6A7D9B2E00000062}" {
  }
  OVT_SupportModifierSpaceJobCondition "{6A7D9B2E00000063}" {
   m_sModifierName "OfficerAssassinated"
  }
 }
 m_aStages {
  OVT_JobStageConfig "{6A7D9B2E00000064}" {
   m_Handler OVT_WaitTillJobAcceptedJobStage "{6A7D9B2E00000065}" {
   }
  }
  OVT_JobStageConfig "{6A7D9B2E00000066}" {
   m_Handler OVT_SpawnFactionCharacterJobStage "{6A7D9B2E00000067}" {
    m_Faction OCCUPYING_FACTION
    m_sCharacterName "Officer"
   }
  }
  OVT_JobStageConfig "{6A7D9B2E00000068}" {
   m_Handler OVT_WaitTillDeadJobStage "{6A7D9B2E00000069}" {
   }
  }
  OVT_JobStageConfig "{6A7D9B2E0000006A}" {
   m_Handler OVT_AddSupportModifierJobStage "{6A7D9B2E0000006B}" {
    m_sModifierName "OfficerAssassinated"
   }
  }
 }
}