OVT_JobConfig {
 m_sTitle "#OVT-Job_PirateRadio"
 m_sDescription "#OVT-Job_PirateRadio_Description"
 m_iReward 500
 m_iRewardXP 20
 m_aConditions {
  OVT_RandomJobCondition "{6A7D9B2E00000039}" {
   m_fChance 0.25
   m_fLowSupportFactor 2
  }
  OVT_TownSupportJobCondition "{6A7D9B2E0000003A}" {
   m_iMaxSupport 50
  }
  OVT_TownPlaceableCountJobCondition "{6A7D9B2E0000003B}" {
   m_sPlaceableName "PirateRadio"
   m_iMaxCount 1
  }
 }
 m_aStages {
  OVT_JobStageConfig "{6A7D9B2E0000003C}" {
   m_Handler OVT_WaitTillJobAcceptedJobStage "{6A7D9B2E0000003D}" {
   }
  }
  OVT_JobStageConfig "{6A7D9B2E0000003E}" {
   m_Handler OVT_PlaceableItemJobStage "{6A7D9B2E0000003F}" {
    m_sPlaceableName "PirateRadio"
    m_bInJobTown 1
   }
  }
 }
}