OVT_JobConfig {
 m_sTitle "#OVT-Job_PropagandaRun"
 m_sDescription "#OVT-Job_PropagandaRun_Description"
 m_iReward 100
 m_iRewardXP 10
 m_aConditions {
  OVT_RandomJobCondition "{6A7D9B2E00000032}" {
   m_fChance 0.4
   m_fLowSupportFactor 2
  }
  OVT_TownSupportJobCondition "{6A7D9B2E00000033}" {
   m_iMaxSupport 75
  }
  OVT_TownPlaceableCountJobCondition "{6A7D9B2E00000034}" {
   m_sPlaceableName "Poster"
   m_iMaxCount 5
  }
 }
 m_aStages {
  OVT_JobStageConfig "{6A7D9B2E00000035}" {
   m_Handler OVT_WaitTillJobAcceptedJobStage "{6A7D9B2E00000036}" {
   }
  }
  OVT_JobStageConfig "{6A7D9B2E00000037}" {
   m_Handler OVT_PlaceableItemJobStage "{6A7D9B2E00000038}" {
    m_sPlaceableName "Poster"
    m_bInJobTown 1
   }
  }
 }
}