OVT_JobConfig {
 m_sTitle "#OVT-Job_SabotageRadioTower"
 m_sDescription "#OVT-Job_SabotageRadioTower_Description"
 m_iReward 450
 m_iRewardXP 25
 m_aConditions {
  OVT_RandomJobCondition "{6A7D9B2E00000054}" {
   m_fChance 0.3
   m_fLowSupportFactor 2
  }
  OVT_TownHasEnemyTowerJobCondition "{6A7D9B2E00000055}" {
  }
 }
 m_aStages {
  OVT_JobStageConfig "{6A7D9B2E00000056}" {
   m_Handler OVT_WaitTillJobAcceptedJobStage "{6A7D9B2E00000057}" {
   }
  }
  OVT_JobStageConfig "{6A7D9B2E00000058}" {
   m_Handler OVT_GetRadioTowerLocationJobStage "{6A7D9B2E00000059}" {
   }
  }
  OVT_JobStageConfig "{6A7D9B2E0000005A}" {
   m_Handler OVT_WaitTillTowerDisabledJobStage "{6A7D9B2E0000005B}" {
   }
  }
 }
}