OVT_DifficultySettings {
 name "Extreme"
 description "#OVT-Difficulty_Extreme_Desc"
 showPlayerOnMap 1
 wantedTimeout 200000
 wantedOneTimeout 280000
 startingResources 2000
 baseResourcesPerTick 500
 resourcesPerTick 1000
 radioTowerSabotageTime 900
 baseSupportRange 1500
 patrolGroupsMin 6
 patrolGroupsMax 9
 defenseGroupsBaseMax 20
 objectiveHarassmentIntervalMinutes 30
 objectiveHarassmentMaxConcurrent 3
 objectiveHarassmentHoldSeconds 120
 objectiveSabotageMissionsRequired 3
 objectiveSabotageHoldSeconds 80
 objectiveSabotageStructuresPerMission 3
 objectiveTowerRecaptureHoldSeconds 360
 objectiveFOBGarrisonMax 5
 objectiveFOBCost 400
 objectiveMaxConcurrentInsertions 4
 objectiveStarvationMinutes 20
 objectiveQRFResourceGate 2000
 startingCash 0
 respawnCost 25
 fastTravelCost 25
 placeableCostMultiplier 3
 buildableCostMultiplier 3
 realEstateCostMultiplier 1.5
 donationIncome 2
 taxIncome 5
 busTicketPrice 50
 baseRecruitCost 1000
 recruitLoadoutFeeMultiplier 1.5
 gunDealerSellPriceMultiplier 0.2
 procurementMultiplier 0.95
 vehiclePriceMultiplier 3
 fuelPricePerLitre 2.5
 threatReductionFactor 0.003
 QRFFastTravelMode DISABLED
 maxQRF 2000
 disguiseDetectionDistance 25
 baseDisguiseEffectiveness 0.6
 wantedReductionMultiplier 0.5
 detectionRangeMultiplier 0.9
 startingItems {
  "{E1A5D4B878AA8980}Prefabs/Items/Equipment/Radios/Radio_R148.et"
 }
}