OVT_DifficultySettings {
 name "Insane"
 description "#OVT-Difficulty_Insane_Desc"
 showPlayerOnMap 1
 wantedTimeout 260000
 wantedOneTimeout 360000
 baseResourcesPerTick 750
 resourcesPerTick 1500
 radioTowerSabotageTime 900
 baseSupportRange 1500
 patrolGroupsMin 8
 patrolGroupsMax 12
 defenseGroupsBaseMax 30
 counterAttackTimeout 45
 startingCash 0
 respawnCost 30
 fastTravelCost 25
 placeableCostMultiplier 4
 buildableCostMultiplier 4
 realEstateCostMultiplier 2
 donationIncome 1
 taxIncome 3
 busTicketPrice 50
 baseRecruitCost 1500
 gunDealerSellPriceMultiplier 0.2
 procurementMultiplier 0.95
 vehiclePriceMultiplier 4
 baseThreat 500
 threatReductionFactor 0.002
 minFastTravelDistance 1000
 QRFFastTravelMode DISABLED
 QRFPointsToWin 150
 maxQRF 3000
 disguiseDetectionDistance 35
 baseDisguiseEffectiveness 0.5
 wantedReductionMultiplier 0.4
 detectionRangeMultiplier 1
 startingItems {
  "{E1A5D4B878AA8980}Prefabs/Items/Equipment/Radios/Radio_R148.et"
 }
}