OVT_DifficultySettings {
 name "Insane"
 description "Recommended for highly experienced servers"
 showPlayerOnMap 1
 wantedTimeout 260000
 wantedOneTimeout 360000
 startingResources 2500
 baseResourcesPerTick 750
 resourcesPerTick 1500
 baseResourceCost 20
 radioTowerRange 2000
 baseSupportRange 1000
 patrolGroupsMin 8
 patrolGroupsMax 12
 defenseGroupsBaseMax 30
 counterAttackTimeout 45
 startingCash 0
 respawnCost 200
 fastTravelCost 100
 placeableCostMultiplier 4
 buildableCostMultiplier 4
 realEstateCostMultiplier 2
 donationIncome 1
 taxIncome 3
 busTicketPrice 75
 baseRecruitCost 1500
 gunDealerSellPriceMultiplier 0.15
 procurementMultiplier 1
 vehiclePriceMultiplier 4
 baseThreat 500
 threatReductionFactor 0.002
 minFastTravelDistance 1000
 QRFFastTravelMode DISABLED
 QRFPointsToWin 150
 maxQRF 3000
 disguiseDetectionDistance 35
 baseDisguiseEffectiveness 0.5
 wantedReductionMultiplier 0.4
 detectionRangeMultiplier 1
 radioTowerSabotageTime 900
 startingItems {
  "{E1A5D4B878AA8980}Prefabs/Items/Equipment/Radios/Radio_R148.et"
 }
}