StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{59A5462B60C888FA}" {
   Id "OVT-Cancel"
   Target_en_us "Cancel"
   Modified 1504005479
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598C5127A5D2149E}" {
   Id "OVT-CannotAfford"
   Target_en_us "You cannot afford that"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A49A9BE80620C3}" {
   Id "OVT-CannotFastTravelDistance"
   Target_en_us "That is too short of a distance to fast travel"
   Modified 1504002241
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A49A9B02ABC32B}" {
   Id "OVT-CannotFastTravelThere"
   Target_en_us "You cannot fast travel there. Must be near an owned house, camp, FOB or controlled base"
   Modified 1504002186
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A49A9B1B4C8E20}" {
   Id "OVT-CannotFastTravelWanted"
   Target_en_us "You cannot fast travel while wanted"
   Modified 1504002202
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5992E2F582B25E27}" {
   Id "OVT-CannotPlaceHere"
   Target_en_us "You cannot place that item here, you must be near a house you own, an FOB or a controlled base"
   Modified 1502807313
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5990833697321087}" {
   Id "OVT-FieldManual_Category_Overthrow_Title"
   Target_en_us "Overthrow"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5992D5041850CA26}" {
   Id "OVT-FieldManual_FastTravel_Text"
   Target_en_us "You must have a map in your inventory to use \"Fast Travel\". The map will open and you can click on any owned house, camp, FOB or base that the resistance currently controls to instantly travel there. You will be charged a small fee for this service according to the difficulty level."
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{599083306EFCACF6}" {
   Id "OVT-FieldManual_MainMenu_Text"
   Target_en_us "The Overthrow Main Menu (default key: U) is how to access most of the features of Overthrow."
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5990833199C7A051}" {
   Id "OVT-FieldManual_MainMenu_Title"
   Target_en_us "Main Menu"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5992D5044118B4C5}" {
   Id "OVT-FieldManual_MapInfo_Text"
   Target_en_us "You must have a map in your inventory to use \"Map Info\". Clicking on this in the main menu will open the map, then you can click anywhere on the map to show info about that location, including any intel known about the area."
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5992D5049E68387B}" {
   Id "OVT-FieldManual_Resistance_Text"
   Target_en_us "Opens a menu allowing you to see info or change settings about the resistance. Officers can assign other officers here or set a tax rate (Default is 0%) that will deposit an amount of the regular income directly to the Resistance Funds instead. Officers can withdraw money from resistance funds here or send it to another player. Any player can donate money to the resistance efforts here as well."
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59908363B46DA2C7}" {
   Id "OVT-GunDealer"
   Target_en_us "Gun Dealer"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59969DFBF96C7EF4}" {
   Id "OVT-IntroHint"
   Target_en_us "Welcome to Overthrow! This is your home, you will respawn here and can fast travel here for a small fee by opening the main menu (Default Key: U). You also own a car parked in your garage."\
   ""\
   "For more info on Overthrow's features and gameplay just have a look at the \"Field Manual\""
   Modified 1503470598
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A2BD308A7926FA}" {
   Id "OVT-LoadStorage"
   Target_en_us "Load Into vehicle"
   Modified 1503943274
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AB67692AD5DBB}" {
   Id "OVT-MainMenu_Build"
   Target_en_us "Build"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AB6769C0D5394}" {
   Id "OVT-MainMenu_CharacterSheet"
   Target_en_us "Character Sheet"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AB6768B0BDF7E}" {
   Id "OVT-MainMenu_FastTravel"
   Target_en_us "Fast Travel"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AB6769FBB6531}" {
   Id "OVT-MainMenu_ManageRecruits"
   Target_en_us "Manage Recruits"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59728272E8EDC4E0}" {
   Id "OVT-MainMenu_MapInfo"
   Target_en_us "Map Info"
   Target_fr_fr "Infos Carte"
   Target_it_it "Info Mappa"
   Target_de_de "Karteninfo"
   Target_es_es "Información del mapa"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AB6769A9A471C}" {
   Id "OVT-MainMenu_Options"
   Target_en_us "Options"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AB67694121E5D}" {
   Id "OVT-MainMenu_Place"
   Target_en_us "Place"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AB676970E6911}" {
   Id "OVT-MainMenu_Resistance"
   Target_en_us "Resistance"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A49A822C192F63}" {
   Id "OVT-Msg-HasPlacedFOB"
   Target_en_us "has placed a new FOB. It is now available for fast travel and more"
   Modified 1504000954
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A49A823A9D330A}" {
   Id "OVT-Msg-NewFOB"
   Target_en_us "New FOB"
   Modified 1504000929
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A49AC5C2FC26C2}" {
   Id "OVT-Msg-VillageControlledOccupying"
   Target_en_us "Resistance has lost control of the village due to low support"
   Modified 1503964017
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A49AC9A028CADB}" {
   Id "OVT-Msg-VillageControlledResistance"
   Target_en_us "Village is now under control by the resistance due to overwhelming support"
   Modified 1503962273
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{599B1780E41380D7}" {
   Id "OVT-MustBeDriver"
   Target_en_us "You must be the driver of the vehicle to fast travel all occupants"
   Modified 1503337948
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A2BD317EE6028A}" {
   Id "OVT-NoVehiclesNearby"
   Target_en_us "There are no vehicles nearby"
   Modified 1503943297
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{599D3A640FAF1233}" {
   Id "OVT-OccupyingFaction"
   Target_en_us "Occupying Faction"
   Modified 1503478151
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{599A1C5F66015FAB}" {
   Id "OVT-Overthrow"
   Target_en_us "Overthrow"
   Modified 1503304714
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AD5529A3EEA5D}" {
   Id "OVT-Place_Camp"
   Target_en_us "Camp"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AD55D632ED8B6}" {
   Id "OVT-Place_EquipmentBox"
   Target_en_us "Equipment Box"
   Status DEVELOPMENT_DONE
   Modified 1502806313
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AD554852E3A84}" {
   Id "OVT-Place_Floodlights"
   Target_en_us "Floodlights"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AD553667F76AF}" {
   Id "OVT-Place_FOB"
   Target_en_us "FOB"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AD55488E14CB4}" {
   Id "OVT-Place_Hedgehog"
   Target_en_us "Hedgehog"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A5462C8A52FFB8}" {
   Id "OVT-Place_NextItem"
   Target_en_us "Next Item"
   Modified 1504005442
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A2BD9099621079}" {
   Id "OVT-Place_Poster"
   Target_en_us "Recruitment Posters"
   Modified 1503863688
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A5462C90703535}" {
   Id "OVT-Place_PrevItem"
   Target_en_us "Previous Item"
   Modified 1504005453
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A5462CB0574E5C}" {
   Id "OVT-Place_RotateLeft"
   Target_en_us "Rotate Left"
   Modified 1504005398
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A5462CB9759E35}" {
   Id "OVT-Place_RotateRight"
   Target_en_us "Rotate Right"
   Modified 1504005538
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AD55456A8B23F}" {
   Id "OVT-Place_Sandbags"
   Target_en_us "Sandbags"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AD552913ABE10}" {
   Id "OVT-Place_Signs"
   Target_en_us "Signs"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5976AC6DDD54D1E4}" {
   Id "OVT-Population"
   Target_en_us "Population"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598EF9FA0D65B880}" {
   Id "OVT-Shop"
   Target_en_us "Shop"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598EF9F5BEC520FE}" {
   Id "OVT-Shop_Buy"
   Target_en_us "Buy"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{599070D91BB49BFF}" {
   Id "OVT-Shop_InStock"
   Target_en_us "In Stock"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598EF98DD5C74403}" {
   Id "OVT-Shop_Open"
   Target_en_us "Open Shop"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598EF9F4548C4AF0}" {
   Id "OVT-Shop_Sell"
   Target_en_us "Sell"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5976AC6DA44FAA95}" {
   Id "OVT-Stability"
   Target_en_us "Stability"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{599EDE889725FB78}" {
   Id "OVT-StabilityMod_CorruptMayor"
   Target_en_us "Corrupt Mayor"
   Modified 1503584566
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{599EDE89679CDCF8}" {
   Id "OVT-StabilityMod_DrugProblems"
   Target_en_us "Drug Problems"
   Modified 1503584598
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{599EDE889FDE918F}" {
   Id "OVT-StabilityMod_OrganizedCrime"
   Target_en_us "Organized Crime"
   Modified 1503584584
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{599EDE88A96FB592}" {
   Id "OVT-StabilityMod_RecentDeath"
   Target_en_us "Recent Deaths"
   Modified 1503584520
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{599EDE88A12DC28E}" {
   Id "OVT-StabilityMod_RecentGunfire"
   Target_en_us "Recent Gunfire"
   Modified 1503584512
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{599EDE88BA907EC8}" {
   Id "OVT-StabilityMod_RecentPatrol"
   Target_en_us "Recent Patrol"
   Modified 1503584536
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A2BDB5E41019D9}" {
   Id "OVT-StabilityMod_StrongEconomy"
   Target_en_us "Strong Economy"
   Modified 1503846400
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{599D315AC7BF1F3F}" {
   Id "OVT-StartGame"
   Target_en_us "Start Game"
   Modified 1503475215
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A45C635CF39E07}" {
   Id "OVT-StorageEmpty"
   Target_en_us "Equipment Box is empty"
   Modified 1503946452
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5976AC6DA03E2264}" {
   Id "OVT-Support"
   Target_en_us "Support"
   Status DEVELOPMENT_DONE
   Modified 1502796262
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A2BDA8428BCAC2}" {
   Id "OVT-SupportMod_RecruitmentPosters"
   Target_en_us "Recruitment Posters"
   Modified 1503843685
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A49A81DADADDD9}" {
   Id "OVT-TooCloseBase"
   Target_en_us "You cannot place that here, it is too close to a military base"
   Modified 1503997278
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A49A8618B96EBF}" {
   Id "OVT-TooCloseBuilding"
   Target_en_us "You cannot place that here, it is too close to a building"
   Modified 1503996764
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A49A81B65FE81A}" {
   Id "OVT-TooCloseTown"
   Target_en_us "You cannot place that here, it is too close to a town"
   Modified 1503997267
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A2BD31647163FE}" {
   Id "OVT-UnloadStorage"
   Target_en_us "Unload from vehicle"
   Modified 1503943258
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A45C63209BFF7C}" {
   Id "OVT-VehicleEmpty"
   Target_en_us "Vehicle is empty"
   Modified 1503946465
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59A550CC7B4FE9CA}" {
   Id "OVT_Mission_Eden_Description"
   Target_en_us "The persistent and dynamic revolution simulator"
   Modified 1504008249
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
 }
}