StringTable {
 TargetPrefix "Target_"
 ItemClassName "CustomStringTableItem"
 Items {
  CustomStringTableItem "{598C5127A5D2149E}" {
   Id "OVT-CannotAfford"
   Target_en_us "You cannot afford that"
   Modified 1502371140
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5990833697321087}" {
   Id "OVT-FieldManual_Category_Overthrow_Title"
   Target_en_us "Overthrow"
   Modified 1502791196
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5992D5041850CA26}" {
   Id "OVT-FieldManual_FastTravel_Text"
   Target_en_us "You must have a map in your inventory to use \"Fast Travel\". The map will open and you can click on any owned house, camp, FOB or base that the resistance currently controls to instantly travel there. You will be charged a small fee for this service according to the difficulty level."
   Modified 1502795360
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{599083306EFCACF6}" {
   Id "OVT-FieldManual_MainMenu_Text"
   Target_en_us "The Overthrow Main Menu (default key: U) is how to access most of the features of Overthrow."
   Modified 1502792059
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5990833199C7A051}" {
   Id "OVT-FieldManual_MainMenu_Title"
   Target_en_us "Main Menu"
   Modified 1502791674
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5992D5044118B4C5}" {
   Id "OVT-FieldManual_MapInfo_Text"
   Target_en_us "You must have a map in your inventory to use \"Map Info\". Clicking on this in the main menu will open the map, then you can click anywhere on the map to show info about that location, including any intel known about the area."
   Modified 1502795168
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5992D5049E68387B}" {
   Id "OVT-FieldManual_Resistance_Text"
   Target_en_us "Opens a menu allowing you to see info or change settings about the resistance. Officers can assign other officers here or set a tax rate (Default is 0%) that will deposit an amount of the regular income directly to the Resistance Funds instead. Officers can withdraw money from resistance funds here or send it to another player. Any player can donate money to the resistance efforts here as well."
   Modified 1502795643
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59908363B46DA2C7}" {
   Id "OVT-GunDealer"
   Target_en_us "Gun Dealer"
   Modified 1502769244
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AB67692AD5DBB}" {
   Id "OVT-MainMenu_Build"
   Target_en_us "Build"
   Modified 1502266276
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AB6769C0D5394}" {
   Id "OVT-MainMenu_CharacterSheet"
   Target_en_us "Character Sheet"
   Modified 1502264761
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AB6768B0BDF7E}" {
   Id "OVT-MainMenu_FastTravel"
   Target_en_us "Fast Travel"
   Modified 1502264752
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AB6769FBB6531}" {
   Id "OVT-MainMenu_ManageRecruits"
   Target_en_us "Manage Recruits"
   Modified 1502264747
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{59728272E8EDC4E0}" {
   Id "OVT-MainMenu_MapInfo"
   Target_en_us "Map Info"
   Target_fr_fr "Infos Carte"
   Target_it_it "Info Mappa"
   Target_de_de "Karteninfo"
   Target_es_es "Información del mapa"
   Modified 1500847782
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AB6769A9A471C}" {
   Id "OVT-MainMenu_Options"
   Target_en_us "Options"
   Modified 1502264743
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AB67694121E5D}" {
   Id "OVT-MainMenu_Place"
   Target_en_us "Place"
   Modified 1502264739
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AB676970E6911}" {
   Id "OVT-MainMenu_Resistance"
   Target_en_us "Resistance"
   Modified 1502264736
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AD5529A3EEA5D}" {
   Id "OVT-Place_Camp"
   Target_en_us "Camp"
   Modified 1502371117
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AD55D632ED8B6}" {
   Id "OVT-Place_EquipmentBoxes"
   Target_en_us "Equipment Boxes"
   Modified 1502283555
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AD554852E3A84}" {
   Id "OVT-Place_Floodlights"
   Target_en_us "Floodlights"
   Modified 1502284055
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AD553667F76AF}" {
   Id "OVT-Place_FOB"
   Target_en_us "FOB"
   Modified 1502371108
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AD55488E14CB4}" {
   Id "OVT-Place_Hedgehog"
   Target_en_us "Hedgehog"
   Modified 1502283914
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AD55456A8B23F}" {
   Id "OVT-Place_Sandbags"
   Target_en_us "Sandbags"
   Modified 1502283872
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598AD552913ABE10}" {
   Id "OVT-Place_Signs"
   Target_en_us "Signs"
   Modified 1502284837
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5976AC6DDD54D1E4}" {
   Id "OVT-Population"
   Target_en_us "Population"
   Modified 1501355587
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598EF9FA0D65B880}" {
   Id "OVT-Shop"
   Target_en_us "Shop"
   Modified 1502633282
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598EF9F5BEC520FE}" {
   Id "OVT-Shop_Buy"
   Target_en_us "Buy"
   Modified 1502634194
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{599070D91BB49BFF}" {
   Id "OVT-Shop_InStock"
   Target_en_us "In Stock"
   Modified 1502639900
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598EF98DD5C74403}" {
   Id "OVT-Shop_Open"
   Target_en_us "Open Shop"
   Modified 1502542544
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{598EF9F4548C4AF0}" {
   Id "OVT-Shop_Sell"
   Target_en_us "Sell"
   Modified 1502634353
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5976AC6DA44FAA95}" {
   Id "OVT-Stability"
   Target_en_us "Stability"
   Modified 1501355622
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
  CustomStringTableItem "{5976AC6DA03E2264}" {
   Id "OVT-Support"
   Target_en_us "Support"
   Modified 1501355613
   Author "Aaron Static"
   LastChanged "Aaron Static"
  }
 }
}