SCR_MapConfig : "{1B8AC767E06A0ACD}Configs/Map/MapFullscreen.conf" {
    m_aModules {
  OVT_MapTerritoryLayer "{6A84C7D2E1F30A64}" {
   m_iDrawOrder 100
   m_sLayerId "territory"
   m_sDisplayName "#OVT-Map_Layer_Territory"
   m_aSiteTypes {
    OVT_TerritorySiteConfig "{6A84C7D2E1F30A65}" {
     m_sId "base"
     m_fWeight 1.6
    }
    OVT_TerritorySiteConfig "{6A84C7D2E1F30A66}" {
     m_sId "town"
     m_fWeight 1
    }
    OVT_TerritorySiteConfig "{6A84C7D2E1F30A67}" {
     m_sId "radiotower"
     m_fWeight 0.7
    }
    OVT_TerritorySiteConfig "{6A84C7D2E1F30A68}" {
     m_sId "fob"
     m_fWeight 0.55
    }
   }
   m_sBandTexture "{B7E8255E75EE66ED}UI/Textures/Map/overthrow_map_diagonal.edds"
  }
  OVT_MapRestrictedAreas "{5994FB639BC86A6B}" {
   m_iDrawOrder 200
   m_sLayerId "restricted"
   m_sDisplayName "#OVT-Map_Layer_Restricted"
  }
  OVT_MapInfluenceLayer "{6A86D1E000000001}" {
   m_iDrawOrder 300
   m_sLayerId "influence"
   m_sDisplayName "#OVT-Map_Layer_Influence"
   m_fLineWidth 6
  }
  OVT_MapThreatGrid "{65B64E3A31FF30CC}" {
   m_bDisableModule 1
   m_iGridSize 250
  }
 }
 m_aUIComponents {
  SCR_MapToolMenuUI "{599C7D68E8F6B9A8}" {
  }
  OVT_MapPlayerLocation "{599454CADA6CF1FB}" {
   m_Layout "{9813B928528DEB08}UI/Layouts/Map/MapPlayerLocation.layout"
  }
  OVT_OverthrowMapUI "{65B12800EE2A785A}" {
   m_bShowSpawnPoints 0
   m_bShowTasks 0
   m_LocationElementLayout "{C03D3AAC437C6E34}UI/Layouts/Map/Core/OVT_MapLocationElement.layout"
   m_InfoPanelLayout "{44E4A9189471C644}UI/Layouts/Map/Core/OVT_MapInfoPanel.layout"
   m_Config OVT_OverthrowMapConfig "{65D338826A81A06A}" : "{E5F4196FBABEF16B}Configs/Map/OverthrowMap.conf" {
   }
  }
  OVT_MapLayersUI "{6A85D1E000000001}" {
   m_bIsExclusive 1
  }
 }
 m_DescriptorDefaultsConfig SCR_MapDescriptorDefaults "{58C89E6280B692A8}" {
  m_aDescriptorDefaults {
   SCR_DescriptorDefIcon "{552A8D0B1ADA90DF}" {
    m_bIsDefaultInvisible 1
   }
   SCR_DescriptorDefText "{554CC89FEF385265}" {
    m_bIsDefaultInvisible 1
   }
  }
 }
}