SCR_MapConfig {
 m_iMapMode SPAWNSCREEN
 m_LayersConfig SCR_MapLayersBase "{6A83D5A000000030}" : "{3CAC09C3E89190F7}Configs/Map/MapLayersDefault.conf" {
 }
 m_MapPropsConfig SCR_MapPropsBase "{6A83D5A000000031}" : "{AF65563F653FED68}Configs/Map/MapPropsDefault.conf" {
 }
 m_aModules {
  SCR_MapCursorModule "{6A83D5A000000032}" : "{5E40C9235FDA4430}Configs/Map/Prefabs/MapCursorModuleDef.conf" {
   m_bEnableCrosshairCoords 1
  }
 }
 m_aUIComponents {
  OVT_RespawnMapUI "{6A83D5A000000033}" {
   m_bShowSpawnPoints 0
   m_bShowTasks 0
   m_LocationElementLayout "{C03D3AAC437C6E34}UI/Layouts/Map/Core/OVT_MapLocationElement.layout"
   m_InfoPanelLayout "{6A83D5A000000075}UI/Layouts/Map/Core/OVT_MapInfoPanelRespawn.layout"
   m_Config OVT_OverthrowMapConfig "{6A83D5A000000034}" : "{6A83D5A000000070}Configs/Map/OverthrowMapRespawn.conf" {
   }
  }
 }
 m_DescriptorVisibilityConfig SCR_MapDescriptorVisibilityBase "{6A83D5A000000035}" : "{4FFDB559B60FC7BC}Configs/Map/MapDescriptorVisibilityDefault.conf" {
 }
 m_DescriptorDefaultsConfig SCR_MapDescriptorDefaults "{6A83D5A000000036}" : "{FF6B20825D4A566C}Configs/Map/MapDescriptorDefaults.conf" {
  m_aDescriptorDefaults {
   SCR_DescriptorDefText "{554CC89FEF385265}" {
    m_bIsDefaultInvisible 1
   }
   SCR_DescriptorDefIcon "{552A8D0B1ADA90DF}" {
    m_bIsDefaultInvisible 1
   }
  }
 }
}
