OVT_OverthrowMapConfig {
 m_aLocationTypes {
  OVT_MapLocationBase "{6A83D5A000000071}" {
   m_sName "Bases"
   m_fRefreshInterval 0
   m_sDisplayName "#OVT-MilitaryBase"
   m_fVisibilityZoom 0
   m_InfoLayout "{EB42E4308B7411B2}UI/Layouts/Map/LocationTypes/OVT_MapInfoBase.layout"
   m_IconImageset "{8479B3B5347DF5CF}UI/Imagesets/MilitarySymbol/ID_D.imageset"
   m_sIconName "Character_Bcg"
   m_bShowDistance 0
   m_bRespawnOnly 1
   m_fShowNameZoom 0
   m_bShowName 1
   m_sResistanceIconName "Character_Bcg"
   m_sEnemyIconName "Character_Bcg"
  }
  OVT_MapLocationFOB "{6A83D5A000000072}" {
   m_sName "FOBs"
   m_fRefreshInterval 0
   m_sDisplayName "#OVT-Place_FOB"
   m_fVisibilityZoom 0
   m_IconImageset "{C7691945DE01FB28}UI/Imagesets/overthrow_mapicons.imageset"
   m_sIconName "fob"
   m_bUseFactionColor 1
   m_FactionType RESISTANCE_FACTION
   m_bShowDistance 0
   m_bRespawnOnly 1
   m_fShowNameZoom 0
   m_bShowName 1
  }
  OVT_MapLocationCamp "{6A83D5A000000073}" {
   m_sName "Camps"
   m_fRefreshInterval 0
   m_sDisplayName "#OVT-Place_Camp"
   m_fVisibilityZoom 0
   m_IconImageset "{C7691945DE01FB28}UI/Imagesets/overthrow_mapicons.imageset"
   m_sIconName "camp"
   m_bUseFactionColor 1
   m_FactionType RESISTANCE_FACTION
   m_bShowDistance 0
   m_bRespawnOnly 1
   m_fShowNameZoom 0
   m_bShowName 1
  }
  OVT_MapLocationHouse "{6A83D5A000000074}" {
   m_sName "Houses"
   m_fRefreshInterval 0
   m_sDisplayName "#OVT-House"
   m_fVisibilityZoom 0
   m_IconImageset "{C7691945DE01FB28}UI/Imagesets/overthrow_mapicons.imageset"
   m_sIconName "house"
   m_bShowDistance 0
   m_bRespawnOnly 1
   m_fShowNameZoom 0
   m_bShowName 1
   m_UnownedHouseColor 0 0 0 0.687
   m_RentedHouseColor 0 0 0 0.906
   m_HomeHouseColor 0.101961 0.596078 0.219608 1
  }
 }
}
