// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/Layouts/HUD/WantedInfo.layout

class OVT_WantedInfoWidgets
{
	static const ResourceName s_sLayout = "{472DF3D2F7500FEB}UI/Layouts/HUD/WantedInfo.layout";
	ResourceName GetLayout() { return s_sLayout; }

	HorizontalLayoutWidget m_WantedLevel;

	RichTextWidget m_WantedText;

	HorizontalLayoutWidget m_Seen;

	RichTextWidget m_SeenText;

	bool Init(Widget root)
	{
		m_WantedLevel = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_WantedLevel"));

		m_WantedText = RichTextWidget.Cast(root.FindAnyWidget("m_WantedText"));

		m_Seen = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_Seen"));

		m_SeenText = RichTextWidget.Cast(root.FindAnyWidget("m_SeenText"));

		return true;
	}
}
