// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/Layouts/HUD/EconomyInfo.layout

class OVT_EconomyInfoWidgets
{
	static const ResourceName s_sLayout = "{3C972A84DC44F671}UI/Layouts/HUD/EconomyInfo.layout";
	ResourceName GetLayout() { return s_sLayout; }

	VerticalLayoutWidget m_EconomyInfoPanel;

	HorizontalLayoutWidget m_Money;

	RichTextWidget m_MoneyText;

	bool Init(Widget root)
	{
		m_EconomyInfoPanel = VerticalLayoutWidget.Cast(root.FindAnyWidget("m_EconomyInfoPanel"));

		m_Money = HorizontalLayoutWidget.Cast(root.FindAnyWidget("m_Money"));

		m_MoneyText = RichTextWidget.Cast(root.FindAnyWidget("m_MoneyText"));

		return true;
	}
}
