OVT_Faction {
 m_sFactionKey "FIA"
 m_bIsPlayable 1
 m_sFlagPrefab "{B85D81962A3F85BA}Prefabs/Props/Fabric/Flags/Flag_1_2_Everon_01.et"
 m_aHighCommandGroups {
  OVT_HighCommandGroupEntry "{6B1C3D0000000010}" {
   m_sKey "sentry_team"
   m_sTitle "#OVT-HC_Group_SentryTeam"
   m_sDescription "#OVT-HC_Group_SentryTeamDesc"
   m_sGroupPrefab "{6E725D44CA973C24}Prefabs/Groups/INDFOR/Group_FIA_SentryTeam.et"
   m_sMapIcon "Infantry_Friend"
  }
  OVT_HighCommandGroupEntry "{6B1C3D0000000011}" {
   m_sKey "mg_team"
   m_sTitle "#OVT-HC_Group_MachineGunTeam"
   m_sDescription "#OVT-HC_Group_MachineGunTeamDesc"
   m_sGroupPrefab "{22F33D3EC8F281AB}Prefabs/Groups/INDFOR/Group_FIA_MachineGunTeam.et"
   m_sMapIcon "Infantry_Friend"
  }
  OVT_HighCommandGroupEntry "{6B1C3D0000000012}" {
   m_sKey "sharpshooter_team"
   m_sTitle "#OVT-HC_Group_SharpshooterTeam"
   m_sDescription "#OVT-HC_Group_SharpshooterTeamDesc"
   m_sGroupPrefab "{6307F42403E9B8A4}Prefabs/Groups/INDFOR/Group_FIA_SharpshooterTeam.et"
   m_sMapIcon "Sniper_Friend"
  }
  OVT_HighCommandGroupEntry "{6B1C3D0000000013}" {
   m_sKey "recon_team"
   m_sTitle "#OVT-HC_Group_ReconTeam"
   m_sDescription "#OVT-HC_Group_ReconTeamDesc"
   m_sGroupPrefab "{2E9C920C3ACA2C6F}Prefabs/Groups/INDFOR/Group_FIA_ReconTeam.et"
   m_sMapIcon "Recon_Friend"
  }
  OVT_HighCommandGroupEntry "{6B1C3D0000000014}" {
   m_sKey "light_fireteam"
   m_sTitle "#OVT-HC_Group_LightFireTeam"
   m_sDescription "#OVT-HC_Group_LightFireTeamDesc"
   m_sGroupPrefab "{1BB20A4B3A53D0F5}Prefabs/Groups/INDFOR/Group_FIA_LightFireTeam.et"
   m_sMapIcon "Infantry_Friend"
  }
  OVT_HighCommandGroupEntry "{6B1C3D0000000015}" {
   m_sKey "at_team"
   m_sTitle "#OVT-HC_Group_AntiTankTeam"
   m_sDescription "#OVT-HC_Group_AntiTankTeamDesc"
   m_sGroupPrefab "{2CC26054775FBA2C}Prefabs/Groups/INDFOR/Group_FIA_Team_AT.et"
   m_sMapIcon "Antitank_Friend"
  }
  OVT_HighCommandGroupEntry "{6B1C3D0000000016}" {
   m_sKey "fireteam"
   m_sTitle "#OVT-HC_Group_FireTeam"
   m_sDescription "#OVT-HC_Group_FireTeamDesc"
   m_sGroupPrefab "{5BEA04939D148B1D}Prefabs/Groups/INDFOR/Group_FIA_FireTeam.et"
   m_sMapIcon "Infantry_Friend"
  }
  OVT_HighCommandGroupEntry "{6B1C3D0000000017}" {
   m_sKey "rifle_squad"
   m_sTitle "#OVT-HC_Group_RifleSquad"
   m_sDescription "#OVT-HC_Group_RifleSquadDesc"
   m_sGroupPrefab "{CE41AF625D05D0F0}Prefabs/Groups/INDFOR/Group_FIA_RifleSquad.et"
   m_sMapIcon "Infantry_Friend"
  }
  OVT_HighCommandGroupEntry "{6B1C3D0000000018}" {
   m_sKey "technical_pkm"
   m_sTitle "#OVT-HC_Group_TechnicalPKM"
   m_sDescription "#OVT-HC_Group_TechnicalPKMDesc"
   m_sGroupPrefab "{6E725D44CA973C24}Prefabs/Groups/INDFOR/Group_FIA_SentryTeam.et"
   m_sVehiclePrefab "{22B327C6752EC4D4}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_PKM_FIA.et"
   m_sMapIcon "Motorized_Friend"
  }
  OVT_HighCommandGroupEntry "{6B1C3D0000000019}" {
   m_sKey "motor_fireteam"
   m_sTitle "#OVT-HC_Group_MotorFireTeam"
   m_sDescription "#OVT-HC_Group_MotorFireTeamDesc"
   m_sGroupPrefab "{1BB20A4B3A53D0F5}Prefabs/Groups/INDFOR/Group_FIA_LightFireTeam.et"
   m_sVehiclePrefab "{F7E9AA0C813EABDA}Prefabs/Vehicles/Wheeled/UAZ469/UAZ469_FIA.et"
   m_sMapIcon "Motorized_Friend"
  }
  OVT_HighCommandGroupEntry "{6B1C3D000000001A}" {
   m_sKey "truck_squad"
   m_sTitle "#OVT-HC_Group_TruckSquad"
   m_sDescription "#OVT-HC_Group_TruckSquadDesc"
   m_sGroupPrefab "{5BEA04939D148B1D}Prefabs/Groups/INDFOR/Group_FIA_FireTeam.et"
   m_sVehiclePrefab "{B70E6D12A8EC2410}Prefabs/Vehicles/Wheeled/Ural4320/Ural4320_FIA_transport_covered.et"
   m_sMapIcon "Motorized_Friend"
  }
 }
}
