// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/Layouts/Menu/MainMenu.layout

class OVT_MainMenuWidgets
{
	static const ResourceName s_sLayout = "{5201CB56B09FB27A}UI/Layouts/Menu/MainMenu.layout";
	ResourceName GetLayout() { return s_sLayout; }

	TextWidget m_TownNameText;

	TextWidget m_TownInfoText;

	ButtonWidget m_MapInfoButton;
	
	OVT_TownManagerComponent m_TownManager;

	bool Init(Widget root)
	{
		m_TownNameText = TextWidget.Cast(root.FindWidget("Panel0.VerticalLayout0.TownInfo.m_TownNameText"));

		m_TownInfoText = TextWidget.Cast(root.FindWidget("Panel0.VerticalLayout0.TownInfo.m_TownInfoText"));

		m_MapInfoButton = ButtonWidget.Cast(root.FindWidget("Panel0.VerticalLayout0.m_MapInfoButton"));
		
		m_TownManager = OVT_TownManagerComponent.GetInstance();

		return true;
	}
	
	void OnUpdate(IEntity player)
	{
		if(!m_TownManager) return;
		
		OVT_TownData town = m_TownManager.GetNearestTown(player.GetOrigin());
		
		m_TownNameText.SetText(town.name);
		m_TownInfoText.SetTextFormat("pop. %1\nStability: %2%\nSupport: %3%", town.population, town.stability, town.support);
	}
}
