// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/Layouts/Menu/MainMenu.layout

class OVT_MainMenuWidgets
{
	static const ResourceName s_sLayout = "{5201CB56B09FB27A}UI/Layouts/Menu/MainMenu.layout";
	ResourceName GetLayout() { return s_sLayout; }

	TextWidget m_TownNameText;

	TextWidget m_TownInfoText;

	bool Init(Widget root)
	{
		m_TownNameText = TextWidget.Cast(root.FindWidget("Panel0.VerticalLayout0.TownInfo.m_TownNameText"));

		m_TownInfoText = TextWidget.Cast(root.FindWidget("Panel0.VerticalLayout0.TownInfo.m_TownInfoText"));

		return true;
	}
}
