// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/Layouts/Menu/PlaceMenu.layout

class OVT_PlaceMenuWidgets
{
	static const ResourceName s_sLayout = "{02AA5A91E0DD49DF}UI/Layouts/Menu/PlaceMenu.layout";
	ResourceName GetLayout() { return s_sLayout; }

	UniformGridLayoutWidget m_BrowserGrid;

	bool Init(Widget root)
	{
		m_BrowserGrid = UniformGridLayoutWidget.Cast(root.FindWidget("Window.Content.SpaceLayout.Alignment.ContentLayout.ContentSegment.m_BrowserGrid"));

		return true;
	}
}
