// Autogenerated by the Generate Class from Layout plugin, version 0.3.0
// Layout file: UI/Layouts/Menu/MainMenu_Modded.layout

class OVT_MainMenuWidgets_Modded
{
	static const ResourceName s_sLayout = "{65BAFB8A482A90B6}UI/Layouts/Menu/MainMenu_Modded.layout";
	ResourceName GetLayout() { return s_sLayout; }

	TextWidget m_TownNameText;

	TextWidget m_TownInfoText;

	// NEW: Added widgets for faction resources and threat
	TextWidget m_OFResourcesText;

	TextWidget m_ResistanceThreatText;

	bool Init(Widget root)
	{
		m_TownNameText = TextWidget.Cast(root.FindAnyWidget("m_TownNameText"));

		m_TownInfoText = TextWidget.Cast(root.FindAnyWidget("m_TownInfoText"));

		// NEW: Initialize the new widgets
		m_OFResourcesText = TextWidget.Cast(root.FindAnyWidget("m_OFResourcesText"));

		m_ResistanceThreatText = TextWidget.Cast(root.FindAnyWidget("m_ResistanceThreatText"));

		return true;
	}
} 