OVT_ResourcesConfig {
 m_aResources {
  OVT_Resource "{6A8E2E3000000010}" {
   m_sId "timber"
   m_sTitle "#OVT-Resource_Timber"
   m_sDescription "#OVT-Resource_Timber_Description"
   m_fCubicMetresPerUnit 0.1
   m_fKgPerUnit 25
   m_iBasePrice 40
   m_iImportable 1
   m_iIllegal 0
  }
  OVT_Resource "{6A8E2E3000000011}" {
   m_sId "cement"
   m_sTitle "#OVT-Resource_Cement"
   m_sDescription "#OVT-Resource_Cement_Description"
   m_fCubicMetresPerUnit 0.05
   m_fKgPerUnit 50
   m_iBasePrice 60
   m_iImportable 1
   m_iIllegal 0
  }
  OVT_Resource "{6A8E2E3000000012}" {
   m_sId "steel"
   m_sTitle "#OVT-Resource_Steel"
   m_sDescription "#OVT-Resource_Steel_Description"
   m_fCubicMetresPerUnit 0.04
   m_fKgPerUnit 90
   m_iBasePrice 120
   m_iImportable 1
   m_iIllegal 0
  }
  OVT_Resource "{6A8E2E3000000013}" {
   m_sId "hardware"
   m_sTitle "#OVT-Resource_Hardware"
   m_sDescription "#OVT-Resource_Hardware_Description"
   m_fCubicMetresPerUnit 0.02
   m_fKgPerUnit 10
   m_iBasePrice 200
   m_iImportable 1
   m_iIllegal 0
  }
 }
}
