OVT_TutorialEntryConfig {
 m_sId "bases-first-capture"
 m_sTitle "#OVT-Tutorial_BasesFirstCapture_Title"
 m_ePresentation NONMODAL
 m_iPriority 0
 m_sFieldManualTitleKey "#OVT-FieldManual_BaseCapture_Title"
 m_aPages {
  OVT_TutorialPage "{6B3C000000000091}" {
   m_sBody "#OVT-Tutorial_BasesFirstCapture_Body"
   m_sImage "{A0BE5DE941B9B766}UI/Textures/Tutorial/bases-first-capture-ui.edds"
  }
 }
 m_aTriggers {
  OVT_TutorialTrigger "{6B3C000000000092}" {
   m_eEvent PLAYER_ENTER_BASE
   m_iMinValue 0
   m_sFilter ""
  }
 }
 m_bEnabled 1
}