OVT_TutorialEntryConfig {
 m_sId "build-first-structure"
 m_sTitle "#OVT-Tutorial_BuildFirstStructure_Title"
 m_ePresentation NONMODAL
 m_iPriority 0
 m_sFieldManualTitleKey "#OVT-FieldManual_FOBs_Title"
 m_aPages {
  OVT_TutorialPage "{6B3C000000000081}" {
   m_sBody "#OVT-Tutorial_BuildFirstStructure_Body"
   m_sImage "{FF2EF388F99AB77E}UI/Textures/Tutorial/build-first-structure-ui.edds"
  }
 }
 m_aTriggers {
  OVT_TutorialTrigger "{6B3C000000000082}" {
   m_eEvent PLAYER_BUILD
   m_iMinValue 0
   m_sFilter ""
  }
 }
 m_bEnabled 1
}