OVT_TutorialEntryConfig {
 m_sId "fuel-depot-built"
 m_sTitle "#OVT-Tutorial_FuelDepotBuilt_Title"
 m_ePresentation NONMODAL
 m_iPriority 0
 m_sFieldManualTitleKey "#OVT-FieldManual_Fuel_Title"
 m_aPages {
  OVT_TutorialPage "{6B4E1F5000000002}" {
   m_sBody "#OVT-Tutorial_FuelDepotBuilt_Body"
   m_sImage ""
  }
 }
 m_aTriggers {
  OVT_TutorialTrigger "{6B4E1F5000000003}" {
   m_eEvent PLAYER_BUILD
   m_iMinValue 0
   m_sFilter "Fuel Depot"
  }
 }
 m_bShowOverUI 1
 m_bEnabled 1
}
