OVT_TutorialEntryConfig {
 m_sId "highcommand-first-open"
 m_sTitle "#OVT-Tutorial_HighCommandFirstOpen_Title"
 m_ePresentation NONMODAL
 m_iPriority 0
 m_sFieldManualTitleKey "#OVT-FieldManual_HighCommand_Title"
 m_aPages {
  OVT_TutorialPage "{6B1C3D0000007401}" {
   m_sBody "#OVT-Tutorial_HighCommandFirstOpen_Body"
   m_sImage ""
  }
  OVT_TutorialPage "{6B1C3D0000007402}" {
   m_sBody "#OVT-Tutorial_HighCommandFirstOpen_Body2"
   m_sImage ""
  }
 }
 m_aTriggers {
  OVT_TutorialTrigger "{6B1C3D0000007403}" {
   m_eEvent MENU_OPENED
   m_iMinValue 0
   m_sFilter "OVT_HighCommandPurchaseContext"
  }
 }
 m_bShowOverUI 1
 m_bEnabled 1
}
