OVT_TutorialEntryConfig {
 m_sId "home-first-open"
 m_sTitle "#OVT-Tutorial_HomeFirstOpen_Title"
 m_ePresentation NONMODAL
 m_iPriority 0
 m_sFieldManualTitleKey "#OVT-FieldManual_YourHome_Title"
 m_aPages {
  OVT_TutorialPage "{6B3C000000000011}" {
   m_sBody "#OVT-Tutorial_HomeFirstOpen_Body"
   m_sImage ""
  }
 }
 m_aTriggers {
  OVT_TutorialTrigger "{6B3C000000000012}" {
   m_eEvent MENU_OPENED
   m_iMinValue 0
   m_sFilter "OVT_RealEstateContext"
  }
 }
 m_bShowOverUI 1
 m_bEnabled 1
}
