OVT_TutorialEntryConfig {
 m_sId "map-first-open"
 m_sTitle "#OVT-Tutorial_MapFirstOpen_Title"
 m_ePresentation NONMODAL
 m_iPriority 0
 m_sFieldManualTitleKey "#OVT-FieldManual_MapAndTravel_Title"
 m_aPages {
  OVT_TutorialPage "{6B3C000000000031}" {
   m_sBody "#OVT-Tutorial_MapFirstOpen_Body"
   m_sImage "{B979553A332EBA6E}UI/Textures/Tutorial/map-first-open-ui.edds"
  }
 }
 m_aTriggers {
  OVT_TutorialTrigger "{6B3C000000000032}" {
   m_eEvent MAP_OPENED
   m_iMinValue 0
   m_sFilter ""
  }
 }
 m_bShowOverUI 1
 m_bEnabled 1
}