OVT_TutorialEntryConfig {
 m_sId "place-first-placeable"
 m_sTitle "#OVT-Tutorial_PlaceFirstPlaceable_Title"
 m_ePresentation NONMODAL
 m_iPriority 0
 m_sFieldManualTitleKey "#OVT-FieldManual_Camps_Title"
 m_aPages {
  OVT_TutorialPage "{6B3C000000000071}" {
   m_sBody "#OVT-Tutorial_PlaceFirstPlaceable_Body"
   m_sImage "{4576F6623F3B12D1}UI/Textures/Tutorial/place-first-placeable-ui.edds"
  }
 }
 m_aTriggers {
  OVT_TutorialTrigger "{6B3C000000000072}" {
   m_eEvent MENU_OPENED
   m_iMinValue 0
   m_sFilter "OVT_PlaceContext"
  }
 }
 m_bShowOverUI 1
 m_bEnabled 1
}