OVT_TutorialEntryConfig {
 m_sId "economy-first-buy"
 m_sTitle "#OVT-Tutorial_EconomyFirstBuy_Title"
 m_ePresentation NONMODAL
 m_iPriority 0
 m_sFieldManualTitleKey "#OVT-FieldManual_Shops_Title"
 m_aPages {
  OVT_TutorialPage "{6B3A000000000002}" {
   m_sBody "#OVT-Tutorial_EconomyFirstBuy_Body"
  }
 }
 m_aTriggers {
  OVT_TutorialTrigger "{6B3A000000000003}" {
   m_eEvent PLAYER_BUY
  }
 }
 m_bEnabled 1
}
