OVT_TutorialEntryConfig {
 m_sId "recruits-first-recruit"
 m_sTitle "#OVT-Tutorial_RecruitsFirstRecruit_Title"
 m_ePresentation NONMODAL
 m_iPriority 0
 m_sFieldManualTitleKey "#OVT-FieldManual_Recruits_Title"
 m_aPages {
  OVT_TutorialPage "{6B3C000000000061}" {
   m_sBody "#OVT-Tutorial_RecruitsFirstRecruit_Body"
   m_sImage "{02D5734F572D5833}UI/Textures/Tutorial/recruits-first-recruit-ui.edds"
  }
 }
 m_aTriggers {
  OVT_TutorialTrigger "{6B3C000000000062}" {
   m_eEvent PLAYER_RECRUIT_ADDED
   m_iMinValue 0
   m_sFilter ""
  }
 }
 m_bEnabled 1
}