OVT_TutorialEntryConfig {
 m_sId "recruits-hold-position"
 m_sTitle "#OVT-Tutorial_RecruitsHoldPosition_Title"
 m_ePresentation NONMODAL
 m_iPriority 0
 m_sFieldManualTitleKey "#OVT-FieldManual_Recruits_Title"
 m_aPages {
  OVT_TutorialPage "{6B4C000000000062}" {
   m_sBody "#OVT-Tutorial_RecruitsHoldPosition_Body"
   m_sImage ""
  }
 }
 m_aTriggers {
  OVT_TutorialTrigger "{6B4C000000000063}" {
   m_eEvent MENU_OPENED
   m_iMinValue 0
   m_sFilter "OVT_RecruitsContext"
  }
 }
 m_bShowOverUI 1
 m_bEnabled 1
}
