OVT_TutorialEntryConfig {
 m_sId "shops-first-gun-dealer"
 m_sTitle "#OVT-Tutorial_ShopsFirstGunDealer_Title"
 m_ePresentation NONMODAL
 m_iPriority 0
 m_sFieldManualTitleKey "#OVT-FieldManual_GunDealers_Title"
 m_aPages {
  OVT_TutorialPage "{6B3C000000000021}" {
   m_sBody "#OVT-Tutorial_ShopsFirstGunDealer_Body"
   m_sImage ""
  }
 }
 m_aTriggers {
  OVT_TutorialTrigger "{6B3C000000000022}" {
   m_eEvent PLAYER_TRANSACTION
   m_iMinValue 0
   m_sFilter "SHOP_GUNDEALER"
  }
 }
 m_bEnabled 1
}
