OVT_TutorialEntryConfig {
 m_sId "wanted-first-level"
 m_sTitle "#OVT-Tutorial_WantedFirstLevel_Title"
 m_ePresentation NONMODAL
 m_iPriority 0
 m_sFieldManualTitleKey "#OVT-FieldManual_WantedSystem_Title"
 m_aPages {
  OVT_TutorialPage "{6B3C000000000041}" {
   m_sBody "#OVT-Tutorial_WantedFirstLevel_Body"
   m_sImage ""
  }
 }
 m_aTriggers {
  OVT_TutorialTrigger "{6B3C000000000042}" {
   m_eEvent PLAYER_WANTED
   m_iMinValue 0
   m_sFilter ""
  }
 }
 m_bEnabled 1
}
