OVT_TutorialEntryConfig {
 m_sId "welcome-nohome"
 m_sTitle "#OVT-Tutorial_WelcomeIntro_Title"
 m_ePresentation MODAL
 m_iPriority 100
 m_sFieldManualTitleKey "#OVT-FieldManual_Welcome_Title"
 m_aPages {
  OVT_TutorialPage "{6B3D000000000011}" {
   m_sBody "#OVT-Tutorial_WelcomeIntro_Body1"
   m_sImage "{AF8287E4E0234A78}UI/Textures/Tutorial/welcome-intro-1-ui.edds"
  }
  OVT_TutorialPage "{6B3D000000000012}" {
   m_sBody "#OVT-Tutorial_WelcomeNohome_Body2"
   m_sImage "{6C355414394F5F27}UI/Textures/Tutorial/welcome-intro-nohome-2-ui.edds"
  }
  OVT_TutorialPage "{6B3D000000000013}" {
   m_sBody "#OVT-Tutorial_WelcomeIntro_Body3"
   m_sImage "{A469006B3686BF14}UI/Textures/Tutorial/welcome-intro-3-ui.edds"
  }
  OVT_TutorialPage "{6B3D000000000014}" {
   m_sBody "#OVT-Tutorial_WelcomeIntro_Body4"
   m_sImage "{BDA04B3CA63A5A16}UI/Textures/Tutorial/welcome-intro-4-ui.edds"
  }
 }
 m_aTriggers {
  OVT_TutorialTrigger "{6B3D000000000015}" {
   m_eEvent PLAYER_SPAWNED
   m_iMinValue 0
   m_sFilter "nohouse"
  }
 }
 m_bEnabled 1
}