OVT_DeploymentRegistry {
 m_sRegistryName "OverthrowDeployments"
 m_aDeploymentConfigs {
  OVT_DeploymentConfig "{65B2DE73341E9E44}" : "{59D486F45F659F95}Configs/Deployment/Deployment_TownPatrol.conf" {
   m_aModules {
    OVT_ReinforcementBehaviorDeploymentModule "{65B2DE7112A2932A}" {
     m_bDeleteOnConditionFail 0
    }
   }
  }
  OVT_DeploymentConfig "{65B67EB8D6A9A3D3}" : "{A1BF4078311A5A60}Configs/Deployment/Deployment_VehiclePatrol_Light.conf" {
   m_aModules {
    OVT_VehicleSpawningDeploymentModule "{65B67EBB9DEFE0A2}" {
     m_fMaxCruiseSpeed 35
    }
   }
   m_iMaxInstances 1
  }
  OVT_DeploymentConfig "{65B51DADF4509EE8}" : "{D85832D9374CFC97}Configs/Deployment/Deployment_VehiclePatrol_Heavy.conf" {
   m_aModules {
    OVT_VehicleSpawningDeploymentModule "{65B51DAFA1CFFAB7}" {
     m_fMaxCruiseSpeed 30
    }
   }
   m_iMaxInstances 1
  }
  OVT_DeploymentConfig "{6B2E4A7C00000007}" : "{6B2E4A7C00000001}Configs/Deployment/Deployment_TowerGarrison.conf" {
  }
  OVT_DeploymentConfig "{6AB2D3E100000007}" : "{6AB2D3E100000001}Configs/Deployment/Deployment_BaseGarrisonPatrol.conf" {
  }
  OVT_DeploymentConfig "{6AB2D3E100000017}" : "{6AB2D3E100000011}Configs/Deployment/Deployment_BaseHeavyPatrol.conf" {
  }
  OVT_DeploymentConfig "{6AB2D3E100000027}" : "{6AB2D3E100000021}Configs/Deployment/Deployment_BaseATSection.conf" {
  }
  OVT_DeploymentConfig "{6AB4E5F200000008}" : "{6AB4E5F200000001}Configs/Deployment/Deployment_BaseDefensePositions.conf" {
  }
  OVT_DeploymentConfig "{6AB4E5F200000018}" : "{6AB4E5F200000011}Configs/Deployment/Deployment_BaseTowerGuards.conf" {
  }
  OVT_DeploymentConfig "{6AB4E5F200000028}" : "{6AB4E5F200000021}Configs/Deployment/Deployment_BaseSniperPositions.conf" {
  }
  OVT_DeploymentConfig "{6AB5F6A300000008}" : "{6AB5F6A300000001}Configs/Deployment/Deployment_BaseCheckpoints.conf" {
  }
  OVT_DeploymentConfig "{6AB5F6A300000018}" : "{6AB5F6A300000011}Configs/Deployment/Deployment_BaseFortifications.conf" {
  }
  OVT_DeploymentConfig "{6AB5F6A300000028}" : "{6AB5F6A300000021}Configs/Deployment/Deployment_BaseParkedVehicles.conf" {
  }
 }
}