OVT_ObjectiveRegistry {
 m_sRegistryName "OverthrowObjectives"
 m_iSelectionCooldownTicks 1
 m_aObjectiveConfigs {
  OVT_ObjectiveConfig "{6BA1000000000011}" : "{6BA1000000000002}Configs/Objective/Objective_TownOffensive.conf" {
  }
  OVT_ObjectiveConfig "{6BA1000000000012}" : "{6BA1000000000003}Configs/Objective/Objective_BaseOffensive.conf" {
  }
 }
}
